spring.datasource.url=jdbc:postgresql://postgres:5432/orders_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8081}
security.username=${SECURITY_USERNAME}
security.password=${SECURITY_PASSWORD}
